{{- with .Values.compositions }}
{{- range . }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.source.repoURL }}
    targetRevision: {{ $.Values.source.targetRevision }}
    path: {{ .path}}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: {{ $.Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ $.Values.syncPolicy.automated.selfHeal }}
---
{{- end }}
{{- end }}